# app/seed_data.py
from datetime import date, time
from .db import SessionLocal, init_db
from .models import User, DoctorAvailability, Appointment, AuditLog, UserRole, ApptStatus

def seed_data():
    """
        This function creates seed data for the database:
        - Call init_db() to create a table if it doesn't exist
        - Add users (admin, doctor, patient)
        - Add doctor's free schedule
        - Add appointments
        - Add activity log (AuditLog)
    """

    # Make sure the tables in the DB are created (Base.metadata.create_all)
    init_db() 

    # Open new session with DB
    with SessionLocal() as session:

        # Create sample users
        admin = User(
            full_name="Admin One",
            username="admin1",
            email="admin@example.com",
            password_hash="hashed_admin_pw",
            role=UserRole.admin,
        )
        doctor1 = User(
            full_name="Dr. Strange",
            username="drstrange",
            email="dr.strange@example.com",
            password_hash="hashed_dr_pw",
            role=UserRole.doctor,
        )
        doctor2 = User(
            full_name="Dr. House",
            username="drhouse",
            email="dr.house@example.com",
            password_hash="hashed_dr_pw2",
            role=UserRole.doctor,
        )
        patient1 = User(
            full_name="Peter Parker",
            username="peterp",
            email="peter@example.com",
            password_hash="hashed_pw1",
            role=UserRole.patient,
        )
        patient2 = User(
            full_name="Tony Stark",
            username="tonystark",
            email="tony@example.com",
            password_hash="hashed_pw2",
            role=UserRole.patient,
        )
        patient3 = User(
            full_name="Natasha Romanoff",
            username="natasha",
            email="natasha@example.com",
            password_hash="hashed_pw3",
            role=UserRole.patient,
        )

        # Add all users to the session
        session.add_all([admin, doctor1, doctor2, patient1, patient2, patient3])
        # Commit to assign user_id of objects (autogenerated by DB)
        session.commit()

        # Create availability for doctors
        avail1 = DoctorAvailability(
            doctor_id=doctor1.user_id,
            available_date=date(2025, 11, 6),
            start_time=time(9, 0),
            end_time=time(12, 0),
        )
        avail2 = DoctorAvailability(
            doctor_id=doctor2.user_id,
            available_date=date(2025, 11, 6),
            start_time=time(13, 0),
            end_time=time(17, 0),
        )
        session.add_all([avail1, avail2])
        session.commit()


        # Create appointments
        appt1 = Appointment(
            patient_id=patient1.user_id,
            doctor_id=doctor1.user_id,
            appointment_date=date(2025, 11, 6),
            start_time=time(9, 30),
            end_time=time(10, 0),
            status=ApptStatus.scheduled,
        )
        appt2 = Appointment(
            patient_id=patient2.user_id,
            doctor_id=doctor2.user_id,
            appointment_date=date(2025, 11, 6),
            start_time=time(14, 0),
            end_time=time(14, 30),
            status=ApptStatus.completed,
        )
        session.add_all([appt1, appt2])
        session.commit()

        # Add activity log (AuditLog)
        log1 = AuditLog(user_id=admin.user_id, action="create_user", details="Added new doctor account")
        log2 = AuditLog(user_id=doctor1.user_id, action="update_availability", details="Set schedule for 2025-11-06")
        log3 = AuditLog(user_id=patient1.user_id, action="book_appointment", details="Appointment with Dr. Strange")

        session.add_all([log1, log2, log3])
        session.commit() # Write all logs to DB

        print("Sample data inserted successfully")


# Entry point: allows running the file directly using the command
# python -m app.seed_data
# or
# python app/seed_data.py
if __name__ == "__main__":
    seed_data()